[env:1MB_ATmega48V]
platform = atmelavr
board = ATmega48
upload_protocol = usbasp
build_flags =
    -Os

[env:1MB_ATmega48PA]
platform = atmelavr
board = ATmega48P
upload_protocol = usbasp
build_flags =
    -Os
