[env:1MB_ATmega48V]
platform = atmelavr
board = ATmega48
build_flags = -Os -D _1MBRD=1
upload_protocol = usbasp

[env:1MB_ATmega48PA]
platform = atmelavr
board = ATmega48P
build_flags = -Os -D _1MBRD=1
upload_protocol = usbasp
